name: branch "master"

on:
  push:
    paths-ignore:
      - '**.md'
  pull_request:
    paths-ignore:
      - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    name: ${{ matrix.config.dirname }}

    strategy:
      fail-fast: false
      matrix:
        config:
        - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz",
            tarname:  "gcc-arm-10.2-2020.11-x86_64-arm-none-eabi.tar.xz",
            dirname:  "gcc-arm-10.2-2020.11-x86_64-arm-none-eabi",
            prefix:   "arm-none-eabi-",
            raspi:    "2" }
        - { url:      "https://developer.arm.com/-/media/Files/downloads/gnu-a/10.2-2020.11/binrel/gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz",
            tarname:  "gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf.tar.xz",
            dirname:  "gcc-arm-10.2-2020.11-x86_64-aarch64-none-elf",
            prefix:   "aarch64-none-elf-",
            raspi:    "3" }

    steps:
    - name: Select 32-bit QEMU
      if: matrix.config.raspi == '2'
      run: |
        echo "CFG_QEMU_BIN=$HOME/local/qemu-6.0.0/bin/qemu-system-arm" >> $GITHUB_ENV
        echo "CFG_QEMU_OPT=-bios" >> $GITHUB_ENV
        echo "CFG_QEMU_IMG=kernel7.img" >> $GITHUB_ENV

    - name: Select 64-bit QEMU
      if: matrix.config.raspi == '3'
      run: |
        echo "CFG_QEMU_BIN=$HOME/local/qemu-6.0.0/bin/qemu-system-aarch64" >> $GITHUB_ENV
        echo "CFG_QEMU_OPT=-kernel" >> $GITHUB_ENV
        echo "CFG_QEMU_IMG=kernel8.img" >> $GITHUB_ENV

    - name: Checkout circle-stdlib
      uses: actions/checkout@v2
      with:
        repository: smuehlst/circle-stdlib
        path: circle-stdlib

    - name: Cache QEMU
      id: qemu-6_0_0-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/qemu-6.0.0
        key: ${{ runner.os }}-qemu-6_0_0

    - name: Clone QEMU Repository
      if: steps.qemu-6_0_0-cache-id.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        repository: smuehlst/qemu
        ref: 2568d421e0e6855b3b45f455bbc90b41b50cb8df
        path: qemu

    - name: Build QEMU   
      if: steps.qemu-6_0_0-cache-id.outputs.cache-hit != 'true'
      run: |
        sudo apt-get install ninja-build
        cd $GITHUB_WORKSPACE/qemu
        git submodule update --init --recursive
        mkdir -p $GITHUB_WORKSPACE/qemu-build
        cd $GITHUB_WORKSPACE/qemu-build
        ../qemu/configure --prefix=$HOME/local/qemu-6.0.0 --target-list=arm-softmmu,aarch64-softmmu
        make -j
        make install

    - name: Cache Compiler ${{ matrix.config.dirname }}
      id: compiler-cache-id
      uses: actions/cache@v1
      with:
        path: ~/local/${{ matrix.config.dirname }}
        key: ${{ runner.os }}-compiler-${{ matrix.config.dirname }}

    - name: Install Compiler ${{ matrix.config.dirname }}
      if: steps.compiler-cache-id.outputs.cache-hit != 'true'
      run: |
        cd
        wget -nv -O ${{ matrix.config.tarname }} ${{ matrix.config.url }}
        tar -x -f ${{ matrix.config.tarname }} -C ~/local
 
    - name: Set Compiler Path ${{ matrix.config.dirname }}
      run: echo "$HOME/local/${{ matrix.config.dirname }}/bin" >> $GITHUB_PATH

    - name: Update submodules
      run: |
        cd $GITHUB_WORKSPACE/circle-stdlib
        git submodule update --init --recursive
                
    - name: Configure circle-stdlib with QEMU support
      run:  |
        cd $GITHUB_WORKSPACE/circle-stdlib
        ./configure -p ${{ matrix.config.prefix }} -r ${{ matrix.config.raspi }} --qemu
        
    - name: Build libraries
      run: make -j -C $GITHUB_WORKSPACE/circle-stdlib

    - name: Build samples
      run: make -C $GITHUB_WORKSPACE/circle-stdlib build-samples
      
    - name: Run smoke test with QEMU
      run: |
        cd $GITHUB_WORKSPACE/circle-stdlib/samples/05-smoketest
        make
        # Extract blank SD card image
        rm -f sdcard.img
        unzip sdcard.img.zip
        # Guard against endless loop in QEMU run (120 CPU secs)
        ulimit -t 120
        $CFG_QEMU_BIN -M raspi${{ matrix.config.raspi }} $CFG_QEMU_OPT $CFG_QEMU_IMG -display none -nographic -semihosting -sd sdcard.img
